#Name- Dhruv Patil
#PRN- 25070123146
#Experiment-10
#Aim- Study of Pandas library

In [26]:
#Introduction to Pandas
# Pandas: Panel Data
'''Used for:
Structured data
EDA
Data cleaning'''

'Used for:\nStructured data\nEDA\nData cleaning'

In [27]:
#1. Import and printing panda series:
import pandas as pd
s= pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [28]:
#2. Create DataFrame
data={
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}
df=pd.DataFrame(data)
print(df)

  Name  Marks
0    A     85
1    B     90
2    C     78

In [29]:
#3. Find the Structure of the Dataframe
df.shape

(3, 2)

In [30]:
#4. Size of Dataframe
df.size

6

In [31]:
#5. Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [32]:
#Display dimensions
df.ndim

2

In [33]:
#6. Check Data Types of each columns
df.dtypes

Name     object
Marks     int64
dtype: object

In [34]:
#7. Access Individual Column
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [35]:
#8. Access specific row
df.loc[1]

Name      B
Marks    90
Name: 1, dtype: object

In [36]:
df.head()
df.tail()

  Name  Marks
0    A     85
1    B     90
2    C     78

In [37]:
df.iloc[1,1]

np.int64(90)

In [38]:
#9. Add a new column:
'''If marks 80-90-first class
If marks>=90-Distinction
If marks>80-Second class'''
df["Grade"]=["First Class","Distinction","Second Class"]
display(df)

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [39]:
#10. Update data in data frame,
    #Change marks of student A to 88.
df.iloc[0,1]=81
df

  Name  Marks         Grade
0    A     81   First Class
1    B     90   Distinction
2    C     78  Second Class

In [40]:
df.loc[1,"Marks"]=95
df

  Name  Marks         Grade
0    A     81   First Class
1    B     95   Distinction
2    C     78  Second Class

In [41]:
#11. Delete a column
df.drop("Grade", axis=1, inplace=True)
df

  Name  Marks
0    A     81
1    B     95
2    C     78

In [42]:
new_df=df.drop("Name",axis=1)
display("the new column is:",new_df)
print()

'the new column is:'

   Marks
0     81
1     95
2     78

In [43]:
#12. To perform basic statistical analysis
mean1=df["Marks"].mean()
mean1

np.float64(84.66666666666667)

In [44]:
min1=df["Marks"].min()
min1

78

In [45]:
max1=df["Marks"].max()
max1

95

In [46]:
#13. Apply condition (filtering)
#Display students scoring more than 80.
df[df["Marks"]>80]

  Name  Marks
0    A     81
1    B     95